name: build

on: [ push ]

jobs:
    build:
        name: Build and Test Binary on PHP ${{ matrix.php-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.1', '8.2', '8.3', '8.4', '8.5']
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none

            - name: Cache composer dependencies
              uses: actions/cache@v4
              with:
                  path: ./vendor
                  key: ${{ runner.os }}-php-8.1-composer-${{ hashFiles('composer.json') }}
                  restore-keys: ${{ runner.os }}-php-8.1-composer-${{ hashFiles('composer.json') }}

            - name: Cache composer dependencies (box)
              uses: actions/cache@v4
              with:
                  path: ./vendor-bin/box/vendor
                  key: ${{ runner.os }}-php-8.1-composer-${{ hashFiles('vendor-bin/box/composer.json') }}
                  restore-keys: ${{ runner.os }}-php-8.1-composer-${{ hashFiles('vendor-bin/box/composer.json') }}

            - name: Install dependencies
              run: composer --no-interaction --optimize-autoloader install

            - name: Build binary
              run: composer build

            - name: Switch to PHP ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: none

            - name: Test binary on PHP ${{ matrix.php-version }}
              run: |
                  # Make binary executable
                  chmod +x ./dist/shed
                  
                  # Test version command
                  echo "Testing --version command..."
                  ./dist/shed --version
